### ISSUE TITLE
TFileCreateParams missing constructor causing invalid access to internal stream 

### ISSUE THREAD

**Issue by wxinix-caliper** [HemulGM/DelphiOpenAI#10]
https://github.com/HemulGM/DelphiOpenAI/blob/main/OpenAI.Files.pas

Line 18, 

TFileCreateParams inherits from TMultipartFormData. However, TFileCreateParams didn't implement its own constructor. Therefore, 
TFileCreateParams.Create will call TObject.Create,  skipping all the initialization code inside TMultipartFormData.Create(...).

This later will result invalid access to Stream object inside TMultipartFormData.

**Comment by HemulGM** [comment]
Yes, it looks like it. Didn't look that there is no standard constructor for TMultipartFormData

**Comment by wxinix-caliper** [comment]
OpenAI.Images,  TImageCreateParams, TImageVariationParams appear to have the same issue -  missing constructors.

**Comment by HemulGM** [comment]
TImageCreateParams - the constructor of the parent is sufficient.

TImageVariationParams - has a constructor

**Comment by wxinix-caliper** [comment]
right.  I meant TImageEditParams (not TImageCreateParams).   I see they are already fixed.
