### ISSUE TITLE
Backward Compatibility -> Compile Error: TThread.GetTickCount64

### ISSUE THREAD

**Issue by Z3R0PTR** [HemulGM/DelphiOpenAI#17]
Hello,

I'm using the Delphi 10.4 CE and had two compile errors:
_[dcc32 Fehler] OpenAI.Images.pas(511): E2003 Undeclared Identifier: 'GetTickCount64'
[dcc32 Fehler] OpenAI.Images.pas(526): E2003 Undeclared Identifier: 'GetTickCount64'_

In _**OpenAI.Images.pas**_ in **_TImagesAzureRoute.Create_** are two occurences of the call _**TThread.GetTickCount64**_. _**GetTickCount64**_ is available since Delphi 11 if I remeber correctly. In previous versions of Delphi only _**GetTickCount**_ is available within _**TThread**_.

Maybe this call can be encapsulated by compiler switches to keep the backward compatibility. I corrected it for myself within the source code, so there is no bigger problem for me, but other developers will lead into this issue too.

**Comment by HemulGM** [comment]
Fixed
