### ISSUE TITLE
Possible bug in TFineTuningCreateParams

### ISSUE THREAD

**Issue by dec** [HemulGM/DelphiOpenAI#21]
Hello there!

First of all, thanks very much again for your work at this project. Trying to upgrade to the version 1.2 in Delphi 10.4 I find the below code in the "OpenAI.FineTuning.pas" unit:

```
{ TFineTuningCreateParams }

function TFineTuningCreateParams.Hyperparameters(const NEpochs: Integer): TFineTuningCreateParams;
begin
  Result := TFineTuningCreateParams(Add('hyperparameters', TJSONObject.Create(TJSONPair.Create('n_epochs', NEpochs))));
end;
```

When compile I get the below error:

`
[dcc64 Error] OpenAI.FineTuning.pas(257): E2250 There is no overloaded version of 'Create' that can be called with these arguments
`

What I do is to apply the below possible solution: basically use TJSONNumber.Create() to properly pass the "NEpochs" argument as a "TJsonValue", which is one of the possible types of the argument expected by the "TJSONPair.Create()" method.

```
{ TFineTuningCreateParams }

function TFineTuningCreateParams.Hyperparameters(const NEpochs: Integer): TFineTuningCreateParams;
begin
  Result := TFineTuningCreateParams(Add('hyperparameters',
   TJSONObject.Create(TJSONPair.Create('n_epochs', TJSONNumber.Create(NEpochs)))));
end;
```

The above change compile as expected, but, since I am not use this specific class (at least not specifically), I am not sure if this is the better possible solution (but I can compile and use the library without problems). Maybe we can use something like below too:

```
{ TFineTuningCreateParams }

function TFineTuningCreateParams.Hyperparameters(const NEpochs: Integer): TFineTuningCreateParams;
begin
  Result := TFineTuningCreateParams(Add('hyperparameters',
   TJSONObject.Create(TJSONPair.Create('n_epochs', IntToStr(NEpochs)))));
end;
```

... since to "TJSONPair.Create()" we can also pass the argument as a string. Maybe this is not a bug nor an error but something that I simply can't properly understand, but, certainly with the original code I can't compile the unit due to the error that I referred above.

I hope this can help in some way!

**Comment by HemulGM** [comment]
Hmm, yes, there is such a thing. In 10.4 there is no JSONPair constructor needed. I'll change it now. Thanks for the info. I'll post in 15 minutes

**Comment by HemulGM** [comment]
Fixed and new release. Thanks
