### ISSUE TITLE
Does the "Regenerate" function in ChatGPT is simply resend the original prompt to ChatGPT server again?

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#22]
Hi,

I want to mimic the "Regenerate" function in ChatGPT interface.

```
    for var Choice in Chat.Choices do
    begin
      ChatHistory.New(TMessageRole.Assistant, Choice.Message.Content, '');
      txtChatReply.Lines.Add(Choice.Message.Content);
      txtChatReply.Lines.Add('---------------');
    end;
```
I just wonder if the regenerated prompt is just another Choice in the current Chat.Choices, or just resending the original prompt and get a new group of Choices(and use the first one)?

**Comment by HemulGM** [comment]
Choice - these are the answer options when the parameter N is greater than 1.So you can change the answer only by sending it again

**Comment by alanccw** [comment]
Thank you so much.
