### ISSUE TITLE
Is the first Choice has the highest probablity?

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#23]
Hi,

After I sending the prompt, I may get multiple Choices, as below:
```
    for Choice in Chat.Choices do
    begin
    end;
```
Is the first Choice has the highest probability? How to know which Choice is better? I only find a property Delta, which seems to be related to this, but cannot find the documentation on this.

Thank you.

**Comment by HemulGM** [comment]
Choices are answer options. Their number depends on the "N" parameter. By default this parameter is 1.
Structures with delta are designed to work with the "Stream" parameter enabled. Which allows you to receive data from the server partially as it is generated.

**Comment by HemulGM** [comment]
For each method or parameter inside the library there is a field with a description. Just hover your mouse over the word

**Comment by HemulGM** [comment]
![image](https://github.com/HemulGM/DelphiOpenAI/assets/22197242/18691700-6bd2-4225-8e1c-cbb425f1bb45)
