### ISSUE TITLE
Timeout error?

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#24]
Hi,

Today when I try to send prompt to ChatGPT-4, I will always receive the following error:
```
Exception class ENetHTTPClientException with message 'Error receiving data: (12002) Operation timeout'
```
Why?

**Comment by HemulGM** [comment]
In the new version, the timeout has been increased to 2 minutes. There is also a setting for setting up a switchout at your discretion.

**Comment by HemulGM** [comment]
Why? Because the server does not respond for a long time.

**Comment by HemulGM** [comment]
Firstly, there are three timeout parameters. Because there are 3 stages of request.
1. Connection (ConnectionTimeout)
2. Sending data (SendTimeout)
3. Receiving data (ResponseTimeout)
You can set different timeouts for all three stages

**Comment by alanccw** [comment]
Thank you so much.
