### ISSUE TITLE
How to deal with the OpenAI exceptions?

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#25]
Today when I call OpenAI APIs, I get the following exception:

Project Test.exe raised exception class OpenAIException with message 'Bad gateway.'.

Can I safely ignore the exception and resend prompt to OpenAI?

Basically, I modify the codes as below:

```
  while True do
    try
      Chat := FOpenAI.Chat.Create(
                procedure(Params: TChatParams)
                begin
                  Params.Messages(FChatHistory.ToArray());
                  Params.Model(FModel);
                end);

      //  If everything is OK, then we will exit
      Break;
    except
      //  Ignore exceptions and restart
      Temp := 'Exception';
    end;
```

**Comment by HemulGM** [comment]
What exactly is the question?

**Comment by alanccw** [comment]
I want to know whether I can ignore the Exception and resend prompt to ChatGPT, as my codes show.

**Comment by HemulGM** [comment]
Exceptions that the library generates, such as OpenAIException are informational.You can do whatever you want with them. 

But ignoring absolutely all exceptions is bad in principle.

**Comment by alanccw** [comment]
OK. Thank you. Then I will ignore OpenAIExceptions  only.
