### ISSUE TITLE
TAudioTranscription size limit

### ISSUE THREAD

**Issue by Himeko7** [HemulGM/DelphiOpenAI#35]
When trying to post a large file, an error triggers **"Maximum content size limit (26214400) exceeded (26405554 bytes read)"**. Is there a way to send the file (and also receive the data back) asynchronously to keep track of the upload/received data? (and not lock the thread while waiting for the response). Thanks

**Comment by HemulGM** [comment]
The library is stupid, so you can perform requests in a separate stream, via TThread or via TTask

```pascal
TTask.Run(
  procedure
  begin
    var Response := OpenAI.Audio.CreateSpeech(
      procedure(Params: TAudioSpeechParams)
      begin
        ...
      end, StreamData);
  end);
```
