### ISSUE TITLE
Can I set a model in TImageCreateParams?

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#37]
Hi,

Currently I am using the following codes to generate images:
```
var Images := OpenAI.Image.Create(
  procedure(Params: TImageCreateParams)
  begin
    Params.Prompt(MemoPrompt.Text);
    Params.ResponseFormat('url');
  end);
try
  for var Image in Images.Data do
    Image1.Bitmap.LoadFromUrl(Image.Url);
finally
  Images.Free;
end;
```
However, the generated image is not very good. So I am thinking of changing the model. Can I set the model for the image parameters?

Also I check the model list, and it seems only the following one is used for image:

dall-e-2

**Comment by HemulGM** [comment]
Hi. 
Just add the model parameter to the parameter list.
```
var Images := OpenAI.Image.Create(
  procedure(Params: TImageCreateParams)
  begin
    Params.Model('your-model-name');  <--- // here
    Params.Prompt(MemoPrompt.Text);
    Params.ResponseFormat('url');
  end);
try
  for var Image in Images.Data do
    Image1.Bitmap.LoadFromUrl(Image.Url);
finally
  Images.Free;
end;
```

**Comment by alanccw** [comment]
Thank you. My code is out-dated again as it does not support Model parameter.

It seems there is only two models, dall-e-2 and dall-e-3? Is that correct?

**Comment by HemulGM** [comment]
Probably yes. Possible models are adjustable by OpenAI
