### ISSUE TITLE
Support to text to speech model?

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#40]
Hi,

Does your code supports the OpenAI text to speech model at https://platform.openai.com/docs/guides/text-to-speech? I cannot find any info in the document, but find some codes that may related to that, such as OpenAI.Component.Reg.pas.

Thank you.

**Comment by HemulGM** [comment]
There is no component of the finished one for this, but the library fully realizes the API OpenAI. Including Text to Speech methods

**Comment by alanccw** [comment]
Thank you.
