### ISSUE TITLE
Frequenly get error "The input prompt cannot be handled by the engine" when calling Dalle-3 model

### ISSUE THREAD

**Issue by alanccw** [HemulGM/DelphiOpenAI#41]
Recently when I call Dalle-3 model, I will frequently get OpenAI exception with the following error message:

“The input prompt cannot be handled by the engine.”

I ask on OpenAI community, but someone said it is related to the library, not OpenAI, see this: https://community.openai.com/t/the-input-prompt-cannot-be-handled-by-the-engine/700460

**Comment by HemulGM** [comment]
You answered the forum correctly. This is a direct response from the server. The program generally has very few own error reports.

It is likely that the server Igor is your request on the basis of some internal rules. You can try to drive away the request through their own "Moderations" tool
