### ISSUE TITLE
Problems in Delphi 11

### ISSUE THREAD

**Issue by ManoloGC** [HemulGM/DelphiOpenAI#42]
Hi,
When I run this code in Delphi 11, I get this error "Error sending data: (12030) La conexión con el servidor finalizó anormalmente.".
Whats the problem?

Thansk.

procedure TForm1.CornerButton1Click(Sender: TObject);
var
 OpenAI: TOpenAI;
begin

  OpenAI := TOpenAI.Create(API_KEY2) ;
  try

  openAI.Organization:=ORGANIZATION_ID;
  var Completions := OpenAI.Completion.Create(
  procedure(Params: TCompletionParams)
  begin
    Params.Prompt(Memo1.Text);
    Params.MaxTokens(2048);
  end);

    try
      for var Choice in Completions.Choices do
        Memo2.Lines.Add(Choice.Index.ToString + ' ' + Choice.Text);
    finally
      Completions.Free;
    end;
  finally
    OpenAI.Free;
  end;
end;

**Comment by HemulGM** [comment]
Watch whether you have an affordable connection to the server. Let me remind you that the API since recently is also not available in a number of countries.
In addition, the servers are often busy and requests are completed with a timeout (it can be increased).

**Comment by ManoloGC** [comment]
its problem of antivirus.

Enviado desde Outlook para Android<https://aka.ms/AAb9ysg>
________________________________
