### ISSUE TITLE
 TFinishReasonHelper.Create procedure give incorrect TFinishReason?

### ISSUE THREAD

**Issue by teraui91** [HemulGM/DelphiOpenAI#44]
unit OpenAI.Chat;

class function TFinishReasonHelper.Create(const Value: string): TFinishReason;
begin
  if Value = 'stop' then
    Exit(TFinishReason.Stop)
  else if Value = 'length' then
    Exit(TFinishReason.Length)
  else if Value = 'function_call' then
    Exit(TFinishReason.FunctionCall)
  else if Value = 'content_filter' then
    Exit(TFinishReason.ContentFilter)
  else if Value = 'null' then
    Exit(TFinishReason.ToolCalls)
  else if Value = 'tool_calls ' then
    Exit(TFinishReason.Null);
  Result := TFinishReason.Stop;
end;

is seem null and tool_calls is incorrect...

**Comment by teraui91** [comment]
function TFinishReasonHelper.ToString: string;
begin
  case Self of
    TFinishReason.Stop:
      Exit('stop');
    TFinishReason.Length:
      Exit('length');
    TFinishReason.FunctionCall:
      Exit('function_call');
    TFinishReason.ContentFilter:
      Exit('content_filter');
    TFinishReason.Null:
      Exit('null');
    TFinishReason.ToolCalls:
      Exit('tool_calls ');
  end;
end;

'tool_calls ' <- has unnecessary i think

**Comment by HemulGM** [comment]
Yes, thanks, I don't understand how it happened. Corrected
